const ContentConstants = {
  GET_CATEGORIES_DATA: "GET_CATEGORIES_DATA",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILED: "GET_CATEGORIES_FAILED",
  GET_CATEGORY_PLAYLIST_DATA: "GET_CATEGORY_PLAYLIST_DATA",
  GET_CATEGORY_PLAYLIST_SUCCESS: "GET_CATEGORY_PLAYLIST_SUCCESS",
  GET_CATEGORY_PLAYLIST_FAILED: "GET_CATEGORY_PLAYLIST_FAILED",
  GET_PLAYLIST_TRACKS_DATA: "GET_PLAYLIST_TRACKS_DATA",
  GET_PLAYLIST_TRACKS_SUCCESS: "GET_PLAYLIST_TRACKS_SUCCESS",
  GET_PLAYLIST_TRACKS_FAILED: "GET_CATEGORY_PLAYLIST_FAILED",
  ADD_PLAYER_TRACK: "ADD_PLAYER_TRACK",
  REMOVE_PLAYER_TRACK: "REMOVE_PLAYER_TRACK",
  SET_PLAYER_HEIGHT: "SET_PLAYER_HEIGHT",
};

export default ContentConstants;
